### PR TITLE
fix: use posix paths for generated lambda construct files

### LINKED ISSUE #2353: Auto-detected lambdas use mixed path separators in .gitignore when generated on Windows
Related to #2347 and #2344

When generating lambda functions on Windows, the generated .gitignore and .gitattributes use mixed platform path separators:

```
-!/src\rotate-secret-function.ts
+!/src/rotate-secret-function.ts
```

### PR DESCRIPTION
**Pull request by jesse-grabowski**
Fixes #2353

---
By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license.

### CODE REVIEW

File: src/awscdk/lambda-function.ts [hunk 1]
```diff
@@ -152,24 +152,24 @@ export class LambdaFunction extends Component {
       );
     }
 
-    const basePath = join(
-      dirname(entrypoint),
-      basename(
+    const basePath = path.posix.join(
```
Comment (jesse-grabowski) [inline src/awscdk/lambda-function.ts:155]: This line is the only functional change

**Review by mrgrain — APPROVED** [review]
Thanks again!
