### PR TITLE
fix(mergify): not all build jobs are considered

### LINKED ISSUE #1382: Mergify config doesn't require `package-` jobs to pass
Ever since #1359, packaging occurs in a different job than the build job.

These packaging jobs are what calls `jsii-pacmak`, which was previously called in the build job. 
However, mergify isn't configured to look at these jobs, allowing (automatic) breaking PR's to be merged.

For example:

https://github.com/cdk8s-team/cdk8s-plus/pull/226

### PR DESCRIPTION
**Pull request by eladb**
Fixes #1382 by synthesizing the filter with all the build jobs. This has to be done lazily because jobs can be added.

BREAKING CHANGE: `AutoMerge` doesn't take a `buildJob` any more. Instead, you can use `addConditions()` or `addConditionsLater()` to qualify the auto-merge.

---
By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license.

### CODE REVIEW

File: src/github/auto-merge.ts [hunk 1]
```diff
@@ -69,16 +64,46 @@ export class AutoMerge extends Component {
...
 
     this.project.addPackageIgnore('/.mergify.yml');
   }
+
+  /**
+   * Adds conditions to the auto merge rule.
+   * @param conditions The conditions to add (mergify syntax)
+   */
+  public addConditions(...conditions: string[]) {
+    this.conditions.push(...conditions);
```
Comment (iliapolo) [inline src/github/auto-merge.ts:85]: Seems like we don't really need the `conditions` array if we already have the `lazyConditions`.

```suggestion
    this.lazyConditions.push({ renderConditions: () => conditions });
```

File: src/github/auto-merge.ts [hunk 2]
```diff
@@ -69,16 +64,46 @@ export class AutoMerge extends Component {
...
+  }
+
+  /**
+   * Adds conditions that will be rendered only during synthesis.
+   * @param later The later
+   */
+  public addConditionsLater(later: IAddConditionsLater) {
```
Comment (iliapolo) [inline src/github/auto-merge.ts:92]:
```suggestion
  public addLazyConditions(later: IAddConditionsLater) {
```

File: src/github/auto-merge.ts [hunk 3]
```diff
@@ -69,16 +64,46 @@ export class AutoMerge extends Component {
...
+
+    for (const later of this.lazyConditions) {
+      output.push(...later.renderConditions());
+    }
+
+    return output;
+  }
+}
+
+export interface IAddConditionsLater {
```
Comment (iliapolo) [inline src/github/auto-merge.ts:107]:
```suggestion
export interface ILazyConditions {
```

File: src/github/auto-merge.ts [hunk 4]
```diff
@@ -69,16 +64,46 @@ export class AutoMerge extends Component {
...
+  renderConditions(): string[];
```
Comment (iliapolo) [inline src/github/auto-merge.ts:108]:
```suggestion
  render(): string[];
```

File: src/github/auto-merge.ts [hunk 5]
```diff
@@ -69,16 +64,46 @@ export class AutoMerge extends Component {
...
     });
 
     this.project.addPackageIgnore('/.mergify.yml');
   }
+
+  /**
+   * Adds conditions to the auto merge rule.
+   * @param conditions The conditions to add (mergify syntax)
+   */
+  public addConditions(...conditions: string[]) {
```
Comment (iliapolo) [inline src/github/auto-merge.ts:84]: I guess we don't strictly need this method since we only add lazy conditions. Maybe drop it for now to keep it clean?

**Review by iliapolo — CHANGES_REQUESTED** [review]

File: src/github/auto-merge.ts (hunk 5 above)
Comment (eladb) [reply src/github/auto-merge.ts:84]: I think that if we have `addConditionsLater()` it makes sense to also have `addConditions()`? It also helps signify the difference between them.

File: src/github/auto-merge.ts (hunk 1 above)
Comment (eladb) [reply src/github/auto-merge.ts:85]: Done.

File: src/github/auto-merge.ts (hunk 2 above)
Comment (eladb) [reply src/github/auto-merge.ts:92]: I actually prefer "addConditionsLater()" because the "later" applies to how we are adding the conditions and not the nature of the condition ("lazy condition" sounds weird). But that's really a matter of personal preference.

File: src/github/auto-merge.ts (hunk 3 above)
Comment (eladb) [reply src/github/auto-merge.ts:107]: Keeping with the "later" semantics (reasons above).

File: src/github/auto-merge.ts (hunk 4 above)
Comment (eladb) [reply src/github/auto-merge.ts:108]: Done.

**Review by iliapolo — APPROVED** [review]
