### PR TITLE
fix: cannot use file path dependencies

### LINKED ISSUE #1777: Error when using file dependencies
It should be possible to use local paths as dependencies as described in the [npm docs](https://docs.npmjs.com/cli/v8/configuring-npm/package-json#local-paths). For example:

```
project.addPeerDeps("jsii-docgen@file:../jsii-docgen")
```

But this currently causes an error message like this:

```
TypeError: Invalid comparator: file:../jsii-docgen
    at Comparator.parse (/home/ec2-user/development/cdkhacks/node_modules/projen/node_modules/semver/classes/comparator.js:38:13)
    at new Comparator (/home/ec2-user/development/cdkhacks/node_modules/projen/node_modules/semver/classes/comparator.js:22:10)
    at /home/ec2-user/development/cdkhacks/node_modules/projen/node_modules/semver/classes/range.js:133:47
    at Array.map (<anonymous>)
    at Range.parseRange (/home/ec2-user/development/cdkhacks/node_modules/projen/node_modules/semver/classes/range.js:133:35)
    at /home/ec2-user/development/cdkhacks/node_modules/projen/node_modules/semver/classes/range.js:34:22
    at Array.map (<anonymous>)
    at new Range (/home/ec2-user/development/cdkhacks/node_modules/projen/node_modules/semver/classes/range.js:34:8)
    at Object.minVersion (/home/ec2-user/development/cdkhacks/node_modules/projen/node_modules/semver/ranges/min-version.js:6:11)
    at NodePackage.renderDependencies (/home/ec2-user/development/cdkhacks/node_modules/projen/lib/javascript/node-package.js:489:46)
```

### PR DESCRIPTION
**Pull request by Chriscbr**
Fixes #1777 

We've supported dependency versions that aren't strictly semver-strings for a while now (see for example: https://github.com/projen/projen/pull/527). This simply makes the logic a little more robust / less prone to causing sudden errors.

---
By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license

### CODE REVIEW

**Comment by pgollucci** [comment]
👍

File: src/javascript/node-package.ts [hunk 1]
```diff
@@ -1406,3 +1406,11 @@ function determineLockfile(packageManager: NodePackageManager) {
 
   throw new Error(`unsupported package manager ${packageManager}`);
 }
+
+function minVersion(version: string): string | undefined {
+  if (semver.validRange(version)) {
+    return semver.minVersion(version)?.version;
+  } else {
+    return version;
```
Comment (kaizen3031593) [inline src/javascript/node-package.ts:1414]: question: what about when someone erroneously supplies an invalid semver version. We don't error out, and maybe they would expect that. Can we attach a warning or something to this? I'm guessing [Annotations](https://github.com/aws/aws-cdk/blob/master/packages/%40aws-cdk/core/lib/annotations.ts) don't exist in projen, so might be wishful thinking.

**Review by kaizen3031593 — APPROVED** [review]
Approved, because I don't have any blocking comments.

File: src/javascript/node-package.ts (hunk 1 above)
Comment (Chriscbr) [reply src/javascript/node-package.ts:1414]: If the semver version is invalid, it will be caught when `yarn install` or `npm install` fails.

File: test/javascript/node-package.test.ts [hunk 2]
```diff
@@ -96,6 +103,14 @@ function mockYarnInstall(
   );
 }
 
+function minVersion(version: string): string | undefined {
```
[the remark this answers is not in the document]
Comment (Chriscbr) [reply test/javascript/node-package.test.ts]: Fair point. Moved it to a shared location
