### PR TITLE
fix(jsii): incompatible version of jsii-docgen in jsii project

### LINKED ISSUE #3789: Incompatible version of jsii-docgen in jsii project
Hello,

I have a CDK lib projen project and keep it upgraded with `npx projen upgrade`.

For some reason, I can't get the upgrade process to pick the latest jsii-docgen version and so I keep getting the following warning:

```
#######################################################################################################
### You are currently using jsii-rosetta@1.x. We recommend upgrading to jsii-rosetta@5.0.x or       ###
### later. This will allow you to use modern TypeScript syntax, and improves compatibility with     ###
### many common dependencies. For example, recent versions of @types/node.                          ###
###                                                                                                 ###
### 5.0.x and subsequent releases of jsii-rosetta use the same major.minor version as the           ###
### TypeScript compiler they are built on. We recommend declaring a minor-pinned (also known as     ###
### "tilde") dependency on jsii-rosetta (e.g: `"jsii-rosetta": "5.0.x"` or                          ###
### `"jsii-rosetta": "~5.0.7"`).                                                                    ###
###                                                                                                 ###
### For more information, see: https://aws.github.io/jsii/compiler-and-rosetta-maintenance/         ###
###                                                                                                 ###
### This warning can be suppressed by setting the JSII_SUPPRESS_UPGRADE_PROMPT environment variable ###
#######################################################################################################
```

Package.json shows the following:

```
"devDependencies": {
    "@types/jest": "^29.5.12",
    "@types/node": "^18",
    "@typescript-eslint/eslint-plugin": "^7",
    "@typescript-eslint/parser": "^7",
    "aws-cdk-lib": "2.149.0",
    "constructs": "10.0.5",
    "eslint": "^8",
    "eslint-config-prettier": "^8.10.0",
    "eslint-import-resolver-typescript": "^3.6.1",
    "eslint-plugin-import": "^2.29.1",
    "eslint-plugin-prettier": "^4.2.1",
    "jest": "^29.7.0",
    "jest-junit": "^15",
    "jsii": "~5.4.0",
    "jsii-diff": "^1.102.0",
    "jsii-docgen": "^8.0.56",
    "jsii-pacmak": "^1.102.0",
    "jsii-rosetta": "~5.4.0",
    "prettier": "^2.8.8",
    "projen": "^0.85.2",
    "standard-version": "^9",
    "ts-jest": "^29.2.4",
    "ts-node": "^10.9.2",
    "typescript": "^5.5.4"
  },
```
instead of resolving to the latest package, which is 10.4.2 and has the correct dependencies for jsii-rosetta etc.

Investigating projen source code I could find jsii-docgen being added as devDependency at the NodeProject without a version, so I figure it should have been upgraded to the latest one.

Other CDK lib projects that depend on this one will also show a warning like this:
```
[3/4] 🔗  Linking dependencies...
warning " > jsii-docgen@9.2.2" has incorrect peer dependency "jsii-rosetta@~v1.85.0 || ~5.0.14 || ~5.1.2".
```

Some additional info:

```
% node -v
v20.17.0
% npm --version
10.8.2
% yarn --version
1.22.22
```

Results from npx projen upgrade

```
upgrade | yarn install --check-files
yarn install v1.22.22                                                                                                   
warning package-lock.json found. Your project contains lock files generated by tools other than Yarn. It is advised not to mix package managers in order to avoid resolution inconsistencies caused by unsynchronized lock files. To clear this warning, remove package-lock.json.
[1/4] 🔍  Resolving packages...                                                                                         
[2/4] 🚚  Fetching packages...                                                                                          
[3/4] 🔗  Linking dependencies...                                                                                       
[4/4] 🔨  Building fresh packages...                                                                                    
✨  Done in 27.74s.                                                                                                     
👾 upgrade | yarn upgrade @types/jest @types/node @typescript-eslint/eslint-plugin @typescript-eslint/parser eslint-config-prettier eslint-import-resolver-typescript eslint-plugin-import eslint-plugin-prettier eslint jest jest-junit jsii-diff jsii-docgen jsii-pacmak jsii-rosetta jsii prettier projen standard-version ts-jest ts-node typescript @types/deep-diff @types/npmlog @types/uuid deep-diff deepmerge npmlog uuid aws-cdk-lib constructs
yarn upgrade v1.22.22                                                                                                   
warning package-lock.json found. Your project contains lock files generated by tools other than Yarn. It is advised not to mix package managers in order to avoid resolution inconsistencies caused by unsynchronized lock files. To clear this warning, remove package-lock.json.
[1/4] 🔍  Resolving packages...                                                                                         
warning eslint > @humanwhocodes/config-array@0.11.14: Use @eslint/config-array instead                                  
warning eslint > @humanwhocodes/config-array > @humanwhocodes/object-schema@2.0.3: Use @eslint/object-schema instead    
warning eslint > file-entry-cache > flat-cache > rimraf@3.0.2: Rimraf versions prior to v4 are no longer supported      
warning eslint > file-entry-cache > flat-cache > rimraf > glob@7.2.3: Glob versions prior to v9 are no longer supported 
warning eslint > file-entry-cache > flat-cache > rimraf > glob > inflight@1.0.6: This module is not supported, and leaks memory. Do not use it. Check out lru-cache if you want a good and tested way to coalesce async requests by a key value, which is much more comprehensive and powerful.
warning jest > jest-cli > jest-config > glob@7.2.3: Glob versions prior to v9 are no longer supported                   
warning jest > @jest/core > jest-runtime > glob@7.2.3: Glob versions prior to v9 are no longer supported                
warning jest > @jest/core > @jest/reporters > glob@7.2.3: Glob versions prior to v9 are no longer supported             
warning jest > @jest/core > @jest/transform > babel-plugin-istanbul > test-exclude > glob@7.2.3: Glob versions prior to v9 are no longer supported
warning jsii-docgen > glob@8.1.0: Glob versions prior to v9 are no longer supported                                     
warning jsii-docgen > glob > inflight@1.0.6: This module is not supported, and leaks memory. Do not use it. Check out lru-cache if you want a good and tested way to coalesce async requests by a key value, which is much more comprehensive and powerful.
warning jsii-rosetta > jsii > downlevel-dts > shelljs > glob@7.2.3: Glob versions prior to v9 are no longer supported   
warning projen > glob@8.1.0: Glob versions prior to v9 are no longer supported                                          
warning standard-version > conventional-changelog-conventionalcommits > q@1.5.1: You or someone you depend on is using Q, the JavaScript Promise library that gave JavaScript developers strong feelings about promises. They can almost certainly migrate to the native JavaScript promise now. Thank you literally everyone for joining me in this bet against the odds. Be excellent to each other.

```

Contents of .projenrc.ts

```
import { awscdk } from 'projen';
const project = new awscdk.AwsCdkConstructLibrary({
  author: 'xx',
  authorAddress: 'xx',
  cdkVersion: '2.149.0',
  defaultReleaseBranch: 'main',
  jsiiVersion: '~5.4.0',
  name: '@druid-networks/druid-constructs',
  projenrcTs: true,
  prettier: true,
  prettierOptions: { settings: { singleQuote: true } },
  repositoryUrl: 'https://github.com/druid-networks/druid-constructs.git',
  bundledDeps: [
    'deep-diff',
    'deepmerge',
    '@types/deep-diff',
    '@types/npmlog',
    'npmlog',
    'uuid',
    '@types/uuid',
  ],
  depsUpgrade: true,
  depsUpgradeOptions: {
    workflow: false,
  },
});

// ignore packages or files
const commonExclude = ['cdk.out', 'yarn-error.log'];
project.npmignore?.exclude(...commonExclude);
project.gitignore.exclude(...commonExclude);

project.synth();

```

What should I do to upgrade jsii-docgen to the latest version?

### PR DESCRIPTION
**Pull request by mrgrain**
Fixes #3789

Requires a minimum version of jsii-docgen that is known to work with all current jsii versions.

---
By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license.

### CODE REVIEW

File: src/cdk/jsii-docgen.ts [hunk 1]
```diff
@@ -9,6 +11,13 @@ export interface JsiiDocgenOptions {
    * @default "API.md"
    */
   readonly filePath?: string;
+
+  /**
+   * A semver versions string to install a specific version of jsii-docgen.
```
Comment (iliapolo) [inline src/cdk/jsii-docgen.ts:16]:
```suggestion
   * A semver version string to install a specific version of jsii-docgen.
```

File: src/cdk/jsii-project.ts [hunk 2]
```diff
@@ -424,7 +424,13 @@ export class JsiiProject extends TypeScriptProject {
     this.npmignore?.include(".jsii");
 
     if (options.docgen ?? true) {
-      new JsiiDocgen(this, { filePath: options.docgenFilePath });
+      // If jsiiVersion is "*", don't specify anything so the user can manage.
+      // Otherwise use a version that is compatible with all supported jsii releases.
+      const docgenVersion = options.jsiiVersion === "*" ? "*" : "^10.4.0";
```
Comment (iliapolo) [inline src/cdk/jsii-project.ts:429]: Will we have to upgrade this every time we add new TS support to docgen?

```suggestion
      const docgenVersion = options.jsiiVersion === "*" ? "*" : "^10.5.0";
```

Comment (mrgrain) [reply src/cdk/jsii-project.ts:429]: That really depends.

In general, yes. When a component decides to set a version constraint, it takes on the responsibility to maintain it. We do that in a large number of places in projen. 

But this specific constraint is wide enough to install the latest version of docgen anyway. It will probably work without intervention.

In practice, projen has a PR to update jsii stuff anyway when a new jsii version is released. So this is really only a little extra.

**Review by iliapolo — APPROVED** [review]
