### PR TITLE
fix(awscdk): integ tests are still not working for libraries

### LINKED ISSUE #1299: CDK integration tests fail with `Emit skipped` in `awscdk-construct` projects
Root cause: when running `ts-node` in `awscdk-construct` projects, it defaults to use `tsconfig.json` which is generated by JSII and does not include the `test/` tree. 

Solution: we need to tell the CDK to run `ts-node` with `tsconfig.dev.json`.

Reported by @jumic - repro: https://github.com/jumic/projen-integ-test

### PR DESCRIPTION
**Pull request by eladb**
1. The `-P` switch for `ts-node` should have appeared before the entrypoint.
2. Implement `tryGetDependency()`

Fixes #1300
Fixes #1299 (again)

---
By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license.

### CODE REVIEW

File: src/dependencies.ts [hunk 1]
```diff
@@ -80,15 +80,37 @@ export class Dependencies extends Component {
...
+   * `type` is not provided and there is more then one dependency type for this
+   * dependency.
+   *
+   * @param name The name of the dependency
+   * @param type The dependency type. If this dependency is defined only for a
+   * single type, this argument can be omitted.
+   *
+   * @returns a copy (cannot be modified) or undefined if there is no match
+   */
+  public tryGetDependency(name: string, type?: DependencyType): Dependency | undefined {
```
Comment (eladb) [inline src/dependencies.ts:108]: @Chriscbr I saw you also added this, but I get credit for also adding a test :-)

**Review by Chriscbr — APPROVED** [review]

**Comment by jumic** [comment]
Thanks for your quick response and the fix. 🚀 Issue resolved. 👍
