### PR TITLE
fix(jsii): error if docgen is explicitly enabled

### LINKED ISSUE #960: Bump throwing error about task already existing
Bump is throwing error about docgen task already exists. This prevents the npm version from bumping successfully, but the version file is increased still. If I remove `docgen: true` from the `.projenrc.js` file , then I there is no `projen bump` command to automatically version.

Projen version:
```
❯ pj --version
0.23.2
```

Bump command with output:
```
❯ pj bump
🤖 bump | condition: ! git log --oneline -1 | grep -q "chore(release):"
🤖 bump | standard-version
✔ bumping version in version.json from 0.0.26 to 0.0.27
✔ Running lifecycle script "postbump"
ℹ - execute command: "npx projen && git add ."
/Users/westibbitts/Data/Eturi/DevOps/cdkconstructs/typescript/eks/node_modules/projen/lib/tasks/tasks.js:54
            throw new Error(`A task with the name ${name} already exists. To override it, call removeTask first and then create the new task.`);
            ^

Error: A task with the name docgen already exists. To override it, call removeTask first and then create the new task.
    at Tasks.addTask (/Users/westibbitts/Data/Eturi/DevOps/cdkconstructs/typescript/eks/node_modules/projen/lib/tasks/tasks.js:54:19)
    at AwsCdkConstructLibrary.addTask (/Users/westibbitts/Data/Eturi/DevOps/cdkconstructs/typescript/eks/node_modules/projen/lib/project.js:113:27)
    at new JsiiDocgen (/Users/westibbitts/Data/Eturi/DevOps/cdkconstructs/typescript/eks/node_modules/projen/lib/jsii-docgen.js:14:32)
    at new JsiiProject (/Users/westibbitts/Data/Eturi/DevOps/cdkconstructs/typescript/eks/node_modules/projen/lib/jsii-project.js:135:13)
    at new ConstructLibrary (/Users/westibbitts/Data/Eturi/DevOps/cdkconstructs/typescript/eks/node_modules/projen/lib/construct-lib.js:17:9)
    at new AwsCdkConstructLibrary (/Users/westibbitts/Data/Eturi/DevOps/cdkconstructs/typescript/eks/node_modules/projen/lib/awscdk-construct.js:82:9)
    at Object.<anonymous> (/Users/westibbitts/Data/Eturi/DevOps/cdkconstructs/typescript/eks/.projenrc.js:3:17)
    at Module._compile (internal/modules/cjs/loader.js:1201:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1221:10)
    at Module.load (internal/modules/cjs/loader.js:1050:32)

✔ outputting changes to CHANGELOG.md
✔ committing version.json and CHANGELOG.md and all staged files
✔ tagging release v0.0.27
```

Projenrc.js file:
```
const { AwsCdkConstructLibrary, ProjectType } = require('projen');

const project = new AwsCdkConstructLibrary({
  author: 'Wes Tibbitts',
  authorAddress: 'wes@eturi.com',
  cdkVersion: '1.116.0',
  defaultReleaseBranch: 'master',
  jsiiFqn: 'projen.AwsCdkConstructLibrary',
  name: '@company/eks',
  repositoryUrl: 'git@gitlab.com:Eturi/devops/cdkconstructs.git',
  projectType: ProjectType.LIB,

  cdkDependencies: [
    '@aws-cdk/aws-eks',
    '@aws-cdk/aws-iam',
    '@aws-cdk/aws-ec2',
    '@aws-cdk/core',
  ],

  python: {
    distName: 'company-eks',
    module: 'company-eks',
  },

  /* AwsCdkConstructLibraryOptions */
  cdkAssert: true, /* Install the @aws-cdk/assert library? */
  // cdkDependencies: undefined,                                               /* Which AWS CDK modules (those that start with "@aws-cdk/") does this library require when consumed? */
  // cdkDependenciesAsDeps: true,                                              /* If this is enabled (default), all modules declared in `cdkDependencies` will be also added as normal `dependencies` (as well as `peerDependencies`). */
  cdkTestDependencies: undefined, /* AWS CDK modules required for testing. */
  // cdkVersionPinning: false,                                                 /* Use pinned version instead of caret version for CDK. */

  /* ConstructLibraryOptions */
  // catalog: undefined,                                                       /* Libraries will be picked up by the construct catalog when they are published to npm as jsii modules and will be published under:. */

  /* JsiiProjectOptions */
  // compat: false,                                                            /* Automatically run API compatibility test against the latest version published to npm after compilation. */
  // compatIgnore: '.compatignore',                                            /* Name of the ignore file for API compatibility tests. */
  docgen: true, /* Automatically generate API.md from jsii. */
  eslint: true, /* Install eslint. */
  // eslintOptions: undefined,                                                 /* Eslint options. */
  // excludeTypescript: undefined,                                             /* Accepts a list of glob patterns. */
  // publishToGo: undefined,                                                   /* Publish Go bindings to a git repository. */
  // publishToMaven: undefined,                                                /* Publish to maven. */
  // publishToNuget: undefined,                                                /* Publish to NuGet. */
  // publishToPypi: undefined,                                                 /* Publish to pypi. */
  // rootdir: '.',                                                             /* undefined */
  sampleCode: true, /* Generate one-time sample in `src/` and `test/` if there are no files there. */

  /* NodePackageOptions */
  // allowLibraryDependencies: true,                                           /* Allow the project to include `peerDependencies` and `bundledDependencies`. */
  // authorEmail: undefined,                                                   /* Author's e-mail. */
  // authorName: undefined,                                                    /* Author's name. */
  // authorOrganization: undefined,                                            /* Author's Organization. */
  // authorUrl: undefined,                                                     /* Author's URL / Website. */
  // autoDetectBin: true,                                                      /* Automatically add all executables under the `bin` directory to your `package.json` file under the `bin` section. */
  // bin: undefined,                                                           /* Binary programs vended with your module. */
  bundledDeps: [
    '@types/js-yaml',
    'axios',
    'console',
    'fs',
    'js-yaml',
  ], /* List of dependencies to bundle into this module. */
  deps: [
    '@types/js-yaml',
    'axios',
    'console',
    'fs',
    'js-yaml',
  ], /* Runtime dependencies of this module. */
  // description: undefined,                                                   /* The description is just a string that helps people understand the purpose of the package. */
  // devDeps: [],                                                              /* Build dependencies for this module. */
  // entrypoint: 'lib/index.js',                                               /* Module entrypoint (`main` in `package.json`). */
  // homepage: undefined,                                                      /* Package's Homepage / Website. */
  keywords: [
    'eks',
  ], /* Keywords to include in `package.json`. */
  // license: 'Apache-2.0',                                                    /* License's SPDX identifier. */
  // licensed: true,                                                           /* Indicates if a license should be added. */
  // maxNodeVersion: undefined,                                                /* Minimum node.js version to require via `engines` (inclusive). */
  // minNodeVersion: undefined,                                                /* Minimum Node.js version to require via package.json `engines` (inclusive). */
  // npmAccess: undefined,                                                     /* Access level of the npm package. */
  // npmDistTag: 'latest',                                                     /* Tags can be used to provide an alias instead of version numbers. */
  // npmRegistryUrl: 'https://registry.npmjs.org',                             /* The base URL of the npm package registry. */
  // npmTaskExecution: NpmTaskExecution.PROJEN,                                /* Determines how tasks are executed when invoked as npm scripts (yarn/npm run xyz). */
  // packageManager: NodePackageManager.YARN,                                  /* The Node Package Manager used to execute scripts. */
  // packageName: undefined,                                                   /* The "name" in package.json. */
  // peerDependencyOptions: undefined,                                         /* Options for `peerDeps`. */
  // peerDeps: [],                                                             /* Peer dependencies for this module. */
  // projenCommand: 'npx projen',                                              /* The shell command to use in order to run the projen CLI. */
  // repository: undefined,                                                    /* The repository is the location where the actual code for your package lives. */
  // repositoryDirectory: undefined,                                           /* If the package.json for your package is not in the root directory (for example if it is part of a monorepo), you can specify the directory in which it lives. */
  // scripts: {},                                                              /* npm scripts to include. */
  // stability: undefined,                                                     /* Package's Stability. */

  /* NodeProjectOptions */
  // antitamper: true,                                                         /* Checks that after build there are no modified files on git. */
  // artifactsDirectory: 'dist',                                               /* A directory which will contain artifacts to be published to npm. */
  buildWorkflow: false, /* Define a GitHub workflow for building PRs. */
  // codeCov: false,                                                           /* Define a GitHub workflow step for sending code coverage metrics to https://codecov.io/ Uses codecov/codecov-action@v1 A secret is required for private repos. Configured with @codeCovTokenSecret. */
  // codeCovTokenSecret: undefined,                                            /* Define the secret name for a specified https://codecov.io/ token A secret is required to send coverage for private repositories. */
  // copyrightOwner: undefined,                                                /* License copyright owner. */
  // copyrightPeriod: undefined,                                               /* The copyright years to put in the LICENSE file. */
  dependabot: false, /* Include dependabot configuration. */
  // dependabotOptions: undefined,                                             /* Options for dependabot. */
  // gitignore: undefined,                                                     /* Additional entries to .gitignore. */
  // jest: true,                                                               /* Setup jest unit tests. */
  // jestOptions: undefined,                                                   /* Jest options. */
  // jsiiReleaseVersion: 'latest',                                             /* Version requirement of `jsii-release` which is used to publish modules to npm. */
  mergify: false, /* Adds mergify configuration. */
  // mergifyAutoMergeLabel: 'auto-merge',                                      /* Automatically merge PRs that build successfully and have this label. */
  // mergifyOptions: undefined,                                                /* Options for mergify. */
  // mutableBuild: true,                                                       /* Automatically update files modified during builds to pull-request branches. */
  // npmignore: undefined,                                                     /* Additional entries to .npmignore. */
  // npmignoreEnabled: true,                                                   /* Defines an .npmignore file. Normally this is only needed for libraries that are packaged as tarballs. */
  // projenDevDependency: true,                                                /* Indicates of "projen" should be installed as a devDependency. */
  // projenUpgradeAutoMerge: undefined,                                        /* Automatically merge projen upgrade PRs when build passes. */
  // projenUpgradeSchedule: [ '0 6 * * *' ],                                   /* Customize the projenUpgrade schedule in cron expression. */
  // projenUpgradeSecret: undefined,                                           /* Periodically submits a pull request for projen upgrades (executes `yarn projen:upgrade`). */
  // projenVersion: undefined,                                                 /* Version of projen to install. */
  // pullRequestTemplate: true,                                                /* Include a GitHub pull request template. */
  // pullRequestTemplateContents: undefined,                                   /* The contents of the pull request template. */
  // releaseBranches: [ 'main' ],                                              /* Branches which trigger a release. */
  // releaseEveryCommit: true,                                                 /* Automatically release new versions every commit to one of branches in `releaseBranches`. */
  // releaseSchedule: undefined,                                               /* CRON schedule to trigger new releases. */
  // releaseToNpm: false,                                                      /* Automatically release to npm when new versions are introduced. */
  releaseWorkflow: false, /* Define a GitHub workflow for releasing from "main" when new versions are bumped. */
  // workflowBootstrapSteps: 'yarn install --frozen-lockfile && yarn projen',  /* Workflow steps to use in order to bootstrap this repo. */
  // workflowContainerImage: undefined,                                        /* Container image to use for GitHub workflows. */
  // workflowNodeVersion: undefined,                                           /* The node version to use in GitHub workflows. */

  /* ProjectOptions */
  // clobber: true,                                                            /* Add a `clobber` task which resets the repo to origin. */
  // devContainer: false,                                                      /* Add a VSCode development environment (used for GitHub Codespaces). */
  // gitpod: false,                                                            /* Add a Gitpod development environment. */
  // logging: {},                                                              /* Configure logging options such as verbosity. */
  // outdir: '.',                                                              /* The root directory of the project. */
  // parent: undefined,                                                        /* The parent project, if this project is part of a bigger project. */
  // projectType: ProjectType.UNKNOWN,                                         /* Which type of project this is (library/app). */
  // readme: undefined,                                                        /* The README setup. */
});
project.synth();
```

### PR DESCRIPTION
**Pull request by eladb**
Disable `docgen` when calling `super()` since `JsiiProject` uses `jsii-docgen` instead of
the normal TypeScript docgen tooling.

Fixes #960

---
By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license.

### CODE REVIEW

File: src/__tests__/util.ts [hunk 1]
```diff
@@ -80,6 +80,11 @@ export function mkdtemp() {
  * files so that the snapshots are human readable.
  */
 export function synthSnapshot(project: Project): any {
+  // defensive: verify that "outdir" is actually in a temporary directory
+  if (!path.resolve(project.outdir).startsWith(os.tmpdir())) {
+    throw new Error('Trying to capture a snapshot of a project outside of tmpdir, which implies this test might corrupt an existing project');
+  }
```
Comment (Chriscbr) [inline src/__tests__/util.ts:86]: Huh - this change seems to be causing builds to fail on my Mac, just in the `java-project.test.ts` test suite.

```
 FAIL  lib/__tests__/java/java-project.test.js (5.479 s)
  ✕ defaults (72 ms)
  ✕ pom options (28 ms)
  ✕ dependencies (26 ms)
  ✕ dependencies via ctor (25 ms)
  ✕ no junit (27 ms)
  ✕ projenrc in java (33 ms)
  ✕ disable projenrc in java (19 ms)

  ● defaults

    Trying to capture a snapshot of a project outside of tmpdir, which implies this test might corrupt an existing project

      84 |   if (!path.resolve(project.outdir).startsWith(os.tmpdir())) {
      85 |     console.error(project.outdir);
    > 86 |     throw new Error('Trying to capture a snapshot of a project outside of tmpdir, which implies this test might corrupt an existing project');
         |           ^
      87 |   }
      88 |
      89 |   const synthed = Symbol.for('synthed');

      at Object.synthSnapshot (src/__tests__/util.ts:86:11)
      at Object.<anonymous> (src/__tests__/java/java-project.test.ts:15:10)
```

Comment (eladb) [reply src/__tests__/util.ts:86]: Sorry!
