### PR TITLE
fix(typescript): eslint task lints projenrcts

### LINKED ISSUE #1831: eslint task doesn't lint projenrc when using projenrc-ts
When starting a typescript project using `--projenrc-ts` the eslint task isn't updated to lint `.projenrc.ts`:

```json5
    // ...
    "eslint": {
      "name": "eslint",
      "description": "Runs eslint against the codebase",
      "steps": [
        {
          "exec": "eslint --ext .ts,.tsx --fix --no-error-on-unmatched-pattern src test build-tools .projenrc.js"
        }
      ]
    },
   // ...
```

### PR DESCRIPTION
**Pull request by andrestone**
fixes #1831 

BREAKING CHANGE: EslintOptions.lintProjenRc is now a string
---
By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license.

### CODE REVIEW

File: src/javascript/eslint.ts [hunk 1]
```diff
@@ -39,10 +39,10 @@ export interface EslintOptions {
   readonly ignorePatterns?: string[];
 
   /**
-   * Should we lint .projenrc.js
-   * @default true
+   * Projenrc file to lint. Use empty string to disable.
+   * @default PROJEN_RC
    */
-  readonly lintProjenRc?: boolean;
+  readonly lintProjenRc?: string;
```
Comment (Chriscbr) [inline src/javascript/eslint.ts:45]: How about we add a new field `lintProjenRcFile` instead and deprecate the existing field? I think could help us avoid a breaking change for users.

Comment (andrestone) [reply src/javascript/eslint.ts:45]: I've considered that but then I thought maybe not many users would use this API directly. Can definitely do it if it's more appropriate.

**Review by Chriscbr — APPROVED** [review]
