### PR TITLE
fix(new): cli fails on windows with RangeError

### LINKED ISSUE #2574: Projen new throws RangeError: Maximum call stack size exceeded
Hello, first time trying to run `npx projen new awscdk-construct` and am getting this error:

```
npx projen new awscdk-construct
RangeError: Maximum call stack size exceeded
    at existsSync (node:fs:301:20)
    at findProjenDir (C:\Users\x\AppData\Roaming\npm\node_modules\projen\lib\cli\index.js:84:29)
    at findProjenDir (C:\Users\x\AppData\Roaming\npm\node_modules\projen\lib\cli\index.js:90:12)
    at findProjenDir (C:\Users\x\AppData\Roaming\npm\node_modules\projen\lib\cli\index.js:90:12)
    at findProjenDir (C:\Users\x\AppData\Roaming\npm\node_modules\projen\lib\cli\index.js:90:12)
    at findProjenDir (C:\Users\x\AppData\Roaming\npm\node_modules\projen\lib\cli\index.js:90:12)
    at findProjenDir (C:\Users\x\AppData\Roaming\npm\node_modules\projen\lib\cli\index.js:90:12)
    at findProjenDir (C:\Users\x\AppData\Roaming\npm\node_modules\projen\lib\cli\index.js:90:12)
    at findProjenDir (C:\Users\x\AppData\Roaming\npm\node_modules\projen\lib\cli\index.js:90:12)
    at findProjenDir (C:\Users\x\AppData\Roaming\npm\node_modules\projen\lib\cli\index.js:90:12)
```

Versions:
- npm: 9.6.3
- npx: 9.6.3
- node: v18.15.0

Things already tried:
- Re-installing Node/npm
- Updating Node/npm
- Clearing node caches etc
- Searched for similar problem in Issues section
- Can find similar problems online but not relating to projen. Solutions seem to be around user written code with recursion problems.

Thank you.

### PR DESCRIPTION
**Pull request by mrgrain**
The filesystem root check in the custom findUp implementation did not account for windows paths.
This was introduced in #2418 

Manually verified the fix on my windows machine.

This is blocking when a new project is created.
Existing projects were only partially affected, as the cli would have successfully found a projen directory unless run outside a projen dir. But there it would have errored anyway.

Fixes #2574

---
By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license.

### CODE REVIEW

**Comment by mrgrain** [comment]
@fynnfluegge FYI

File: src/util.ts [hunk 1]
```diff
@@ -447,3 +447,40 @@ export function anySelected(options: (boolean | undefined)[]): boolean {
...
+
+/**
+ * Checks if a path is a FS root
+ *
+ * Optional uses a provided OS specific path implementation,
+ * defaults to use the implementation for the current OS.
+ *
+ * @internal
+ */
+export function isRoot(dir: string, osPathLib: typeof path = path): boolean {
```
Comment (mrgrain) [inline src/util.ts:459]: `osPathLib` is needed for testing. Since this is a purely internal helper, this is acceptable.

**Review by Naumel — APPROVED** [review]

**Comment by fynnfluegge** [comment]
> @fynnfluegge FYI

Uff yeah sorry, totally forgot that windows root path differs 🤦‍♂️

File: src/util.ts [hunk 2]
```diff
@@ -447,3 +447,40 @@ export function anySelected(options: (boolean | undefined)[]): boolean {
...
+): string | undefined {
+  if (existsSync(path.resolve(cwd, lookFor))) {
+    return cwd;
+  }
+
+  if (isRoot(cwd)) {
+    return undefined;
+  }
+
+  return findUp(lookFor, path.resolve(cwd, ".."));
```
Comment (RomainMuller) [inline src/util.ts:485]: How about:

```ts
  const parent = path.dirname(cwd);
  if (parent === cwd) {
    // This is a root
    return undefined;
  }
  return findUp(lookFor, parent);
```

It feels weird to me to use `path.resolve`, especially as this is an "expensive" call, compared to just cutting off with `path.dirname`...

A file system root's directory name is... itself.

File: src/util.ts (hunk 1 above)
Comment (RomainMuller) [reply src/util.ts:459]: This function is no longer used in the actual feature code path...

Comment (mrgrain) [reply src/util.ts:459]: Oof. Thanks!

**Review by RomainMuller — APPROVED** [review]
