### PR TITLE
feat(node): package manifest "bugs" field

### LINKED ISSUE #1369: Missing 'bugs' attribute of package manifest in javascript.NodePackageOptions interface
According to https://docs.npmjs.com/cli/v7/configuring-npm/package-json#bugs, a `bugs` field should be available inside npm package manifests. This is not defined within [`src/javascript/node-package.ts::NodePackageOptions`](https://github.com/projen/projen/blob/main/src/javascript/node-package.ts).

### PR DESCRIPTION
**Pull request by tiararodney**
Adds support for node package manifest `bugs` field via `issueTrackerOptions` in
`src/javascript/node-package.ts::NodePackageOptions`

Resolves #1369

---
By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license.

### CODE REVIEW

File: src/javascript/node-package.ts [hunk 1]
```diff
@@ -248,6 +248,11 @@ export interface NodePackageOptions {
    */
   readonly npmRegistry?: string;
 
+  /**
+   * Options for issue tracking.
+   */
+  readonly issueTrackerOptions?: IIssueTrackerOptions;
```
Comment (eladb) [inline src/javascript/node-package.ts:254]: I'd flatten this into simply:

```suggestion
  readonly bugsEmail?: string;
  readonly bugsUrl?: string;
```

we prefer less hierarchy to improve discoverability

**Review by eladb — CHANGES_REQUESTED** [review]

**Review by eladb — CHANGES_REQUESTED** [review]
Please add a unit test

File: src/javascript/node-package.ts (hunk 1 above)
Comment (tiararodney) [reply src/javascript/node-package.ts]: I see... 🕺 Ok, i've flattened the properties to accommodate your requirements, however i wasn't sure on the design of evaluation logic for the `bugs` property of the `manifest` object. Since properties of the `manifest` object, which are empty objects, are being preserved, further evaluation of `bugsEmail` and `bugsUrl` is required.
I chose a ternary operation since this introduces the least complexity. I hope this is fine.

**Review by eladb — APPROVED** [review]
Looks great!

**Comment by tiararodney** [comment]
@eladb Sorry for the high commit frequency... 🙈 I am a simple person, i use Bitbucket. 👩‍🦼 Still getting used to Github Actions...

**Review by eladb — APPROVED** [review]
