### PR TITLE
fix: release.yml cannot be modified with escape hatches

### LINKED ISSUE #1103: Escape hatches do not work for release.yml
Escape hatches work as usual for most GitHub workflow files:

```js
const workflow = project.tryFindObjectFile('.github/workflows/build.yml');
workflow.addOverride('env.SERVER', 'production');
```

But `tryFindObjectFile` returns undefined for `.github/workflows/release.yml` because it gets created during preSynthesis of the `Release` component. We should find a way to generate the workflow using token values / lazy values so that the functionality works normally.

We should also think of ways to prevent this kind of error in the future, perhaps by limiting the kinds of actions that can be performed during pre/post synthesis (?), or by using some kind of linting rule, etc.

### PR DESCRIPTION
**Pull request by Chriscbr**
Fixes #1103

Resolves a bug where the workflows generated by the `Release` component cannot be accessed or modified using escape hatches because they are generated during the `preSynthesize()` stage of the component lifecycle.

This requires making some changes to `Publisher`, which `Release` relies upon, so that it can provide a link to the jobs it will generate even if `Publisher`'s jobs are not all available at the time construction finishes.

In addition, workflows that are not created via the `github.addWorkflow` method were not getting added to `GitHub` so they could not be discovered with `tryFindWorkflow`. This is fixed by adding a register hook within the `GithubWorkflow` constructor.

---
By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license.

### CODE REVIEW

File: src/github/workflows.ts [hunk 1]
```diff
@@ -46,16 +46,20 @@ export class GithubWorkflow extends Component {
...
 
   private events: workflows.Triggers = { };
   private jobs: Record<string, workflows.Job> = { };
+  private _providers = new Array<IJobProvider>();
 
   constructor(github: GitHub, name: string, options: GithubWorkflowOptions = {}) {
     super(github.project);
 
+    // register to catch duplicate workflow name errors early
+    github._registerWorkflow(name, this);
```
Comment (Chriscbr) [inline src/github/workflows.ts:61]: An alternative to tracking workflows in `GitHub` is would be to do a search for all components that are `instanceof GithubWorkflow` whenever someone accesses `github.workflows` or calls `github.tryFindWorkflow()`. I don't have a strong opinion on which way to do this / I'm open to trying that instead if this `_registerWorkflow` hook is undesirable

File: src/release/publisher.ts [hunk 2]
```diff
@@ -67,7 +67,7 @@ export interface PublisherOptions {
  *
  * Under the hood, it uses https://github.com/aws/jsii-release
  */
-export class Publisher extends Component {
+export class Publisher extends Component implements IJobProvider {
```
Comment (Chriscbr) [inline src/release/publisher.ts:70]: Instead of having `Publisher` implement `IJobProvider`, I could create a separate component that is generated by `Publisher` to isolate the behavior

**Comment by Chriscbr** [comment]
I'm not sure I love this solution, though it does work. Open to other ideas of course. :)

It's worth mentioning this bug also exists in `UpgradeDependencies` -- that component generates resources at pre-synth time because it requires a list of all dependenciess and a list of all `Release` branches. So neither the workflow nor task generated by it are can be escape hatched around.

File: src/github/workflows.ts (hunk 1 above)
Comment (eladb) [reply src/github/workflows.ts:61]: Might be more idiomatic to look up than to register. I think this is how findFile works.

File: src/github/workflows.ts [hunk 3]
```diff
@@ -100,12 +104,28 @@ export class GithubWorkflow extends Component {
     };
   }
 
+  /** @internal */
+  public _addJobsFromProvider(provider: IJobProvider) {
```
Comment (eladb) [inline src/github/workflows.ts:108]: Add docs

File: src/github/workflows.ts [hunk 4]
```diff
@@ -208,3 +228,10 @@ function arrayOrScalar<T>(arr: T[] | undefined): T | T[] | undefined {
   }
   return arr;
 }
+
+export interface IJobProvider {
+  /**
+   * A collection of jobs that may be dynamically generated.
+   */
+  readonly jobs: Record<string, workflows.Job>;
```
Comment (eladb) [inline src/github/workflows.ts:236]: I'd use a method instead of a property here to signal that this can be late bound.

Something like `renderJobs()`

File: src/github/workflows.ts (hunk 3 above)
Comment (eladb) [inline src/github/workflows.ts:108]: I'd make this public can all it `addJobsLater()`

**Review by eladb — CHANGES_REQUESTED** [review]
Generally like the design. A few semantic comments

File: src/github/workflows.ts (hunk 3 above)
Comment (Chriscbr) [reply src/github/workflows.ts]: Done

Comment (Chriscbr) [reply src/github/workflows.ts]: Good suggestion. I like how colloquial the name sounds

File: src/github/github.ts [hunk 5]
```diff
@@ -107,6 +101,12 @@ export class GitHub extends Component {
...
    */
   public tryFindWorkflow(name: string): undefined | GithubWorkflow {
-    return this._workflows[name];
+    for (const workflow of this.workflows) {
+      if (workflow.name === name) {
+        return workflow;
+      }
+    }
+
+    return undefined;
```
Comment (eladb) [inline src/github/github.ts:110]:
```suggestion
    return this.workflows.find(w => w.name === name);
```

**Review by eladb — APPROVED** [review]
