### PR TITLE
fix: Mergify used deprecated `strict mode` in `merge` action

### LINKED ISSUE #1240: Mergify strict mode brown out
Mergify has [deprecated strict](https://blog.mergify.com/strict-mode-deprecation/)  mode with a brownout scheduled for `December 6th, 2021`

This means that the `merge` action should be replaced with a `queue` action and the [mergify class](https://github.com/projen/projen/blob/main/src/github/mergify.ts) needs to be updated to support `queue_rules` in addition to the current `pull_request_rules`

### LINKED ISSUE #1502: mergify: Strict Mode Deprecation
In this ci check, I got `The Mergify configuration is invalid`.

https://github.com/neilkuan/cdk-certbot-dns-route53/pull/199/checks?check_run_id=4758141003

Strict Mode Deprecation
see this blog: https://blog.mergify.com/strict-mode-deprecation/

example:
```
pull_request_rules:
  - name: automatic merge
    conditions:
      - base=main
      - "#approved-reviews-by>=1"
      - "#changes-requested-reviews-by=0"
      - label!=work-in-progress
      - check-success=ci-one
      - check-success=ci-two
    actions:
      merge:
        method: merge
        strict: smart
```

need to change like this:
```bash
queue_rules:
  - name: default
    conditions:
      # Conditions to get out of the queue (= merged)
      - check-success=ci-one
      - check-success=ci-two

pull_request_rules:
  - name: automatic merge
    conditions:
      - base=main
      - "#approved-reviews-by>=1"
      - "#changes-requested-reviews-by=0"
      - label!=work-in-progress
      - check-success=ci-one
      - check-success=ci-two
    actions:
      queue:
        method: merge
        name: default
```

### PR DESCRIPTION
**Pull request by bmiller08**
Strict mode for Mergify was [removed on January 10th, 2022](https://blog.mergify.com/strict-mode-deprecation/). This PR adds the needed Mergify queue (`MergifyQueue`) and reworks the default rule to utilize a `default` queue.

Fixes #1502
Fixes #1240

---
By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license.

### CODE REVIEW

File: src/github/mergify.ts [hunk 1]
```diff
@@ -49,13 +64,30 @@ export class Mergify extends Component {
...
   public addRule(rule: MergifyRule) {
     this.rules.push(rule);
     if (this.yamlFile == null) {
       this.yamlFile = new YamlFile(this.project, ".mergify.yml", {
         obj: {
+          queue_rules: this.queues,
+          pull_request_rules: this.rules,
+        },
+      });
+    }
```
Comment (Chriscbr) [inline src/github/mergify.ts:82]: Please extract this "creating yaml file" logic to a private function so that it's not duplicated between the two methods

File: .mergify.yml [hunk 2]
```diff
@@ -1,17 +1,28 @@
...
     actions:
       merge:
-        method: squash
         commit_message_template: |-
           {{ title }} (#{{ number }})
 
           {{ body }}
-        strict: smart
-        strict_method: merge
       delete_head_branch: {}
```
Comment (Chriscbr) [inline .mergify.yml:22]: Based on the examples in this blog post [here](https://blog.mergify.com/strict-mode-deprecation/), I think we can remove the `merge` action from pull_request_rules since we are adding in the `queue` action.

File: .mergify.yml [hunk 3]
```diff
@@ -1,17 +1,28 @@
...
+      queue:
+        method: merge
+        name: default
```
Comment (Chriscbr) [inline .mergify.yml:25]: I believe the method should be `squash` to be guarantee the same behavior as the previous mergify configuration.

Also, we should copy the `commit_message_template` field here

**Review by Chriscbr — CHANGES_REQUESTED** [review]
Thanks for submitting a PR to fix this @bmiller08 ! A few small comments 🙂

File: src/github/mergify.ts (hunk 1 above)
Comment (bmiller08) [reply src/github/mergify.ts]: Good call. Done.

File: .mergify.yml (hunk 2 above)
Comment (bmiller08) [reply .mergify.yml:22]: Sure. With moving the commit message merge will be empty. Removed.

File: .mergify.yml (hunk 3 above)
Comment (bmiller08) [reply .mergify.yml:25]: Done.

**Review by Chriscbr — APPROVED** [review]
👍

**Comment by bmiller08** [comment]
Fixed the issue with the build and the mergify file not being updated. Not sure why it didn't update when I built locally the first time.

**Comment by Chriscbr** [comment]
> Not sure why it didn't update when I built locally the first time.

Hmm - one thing that could have happened was after updating your code, running `build` may have synthesized this repo's `.projenrc.js` and _then_ compiled the new code. We can probably change the build steps to re-synthesize afterwards as well, since I think this happens pretty often.

**Comment by bmiller08** [comment]
> > Not sure why it didn't update when I built locally the first time.
> 
> Hmm - one thing that could have happened was after updating your code, running `build` on your local machine may have synthesized this repo's `.projenrc.js` and _then_ compiled the new code. We can probably change the build steps to re-synthesize afterwards as well, since I think this happens pretty often.

Happened when I originally submitted the PR as well. So, perhaps that is it.
