### PR TITLE
fix: projen new not working with some of the new discovery changes

### LINKED ISSUE #748: projen new command does not download external library anymore since version 0.17.69
projen new command with external library seems to not download the package since version projen@0.17.69
eg:
```projen new --from @<EXTERNAL_LIB> <TEMPLATE>```

It worked until version 0.17.68

### PR DESCRIPTION
**Pull request by kcwinner**
Fixes #748 

* Fixed the discovery of external types when resolving the project
* Fixed the `newProjectFromModule` directory handling
* Added a unit test for testing external packages - currently points to one of my packages because that's the one I had on hand

---
By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license.

### CODE REVIEW

File: src/cli/cmds/new.ts [hunk 1]
```diff
@@ -277,7 +277,7 @@ async function newProjectFromModule(baseDir: string, spec: string, args: any) {
  * @param args Command line arguments
  * @param additionalProps Additional parameters to include in .projenrc.js
  */
-async function newProject(baseDir: string, type: inventory.ProjectType, args: any, additionalProps?: Record<string, string>) {
+async function newProject(baseDir: string, type: inventory.ProjectType, args: any, additionalProps?: Record<string, any>) {
```
Comment (kcwinner) [inline src/cli/cmds/new.ts:280]: These now get stringified further down the chain in `render-options.ts`. So array were becoming a string

**Review by eladb — APPROVED** [review]

File: src/inventory.ts [hunk 2]
```diff
@@ -116,11 +116,18 @@ export function discover(...moduleDirs: string[]) {
...
 export function resolveProjectType(projectFqn: string) {
   const manifest = readJsiiManifest(projectFqn);
+
   const jsii: JsiiTypes = {};
   for (const [fqn, type] of Object.entries(manifest.types as JsiiTypes)) {
     jsii[fqn] = type;
   }
 
+  // Read Projen JSII types
+  const projenManifest = readJsiiManifest('projen');
```
Comment (kcwinner) [inline src/inventory.ts:126]: Happy to change this however might be better.
