### PR TITLE
fix: pnpm not installed in workflows

### LINKED ISSUE #1026: GitHub action should install pnpm when packageManager: NodePackageManager.PNPM,
When creating an `AwsCdkConstructLibrary`, I wanted to try `pnpm`. I did
```ts
const { AwsCdkConstructLibrary, FileBase, TextFile, NodePackageManager } = require('projen');
const cdkVersion = 'v2.0.0-rc.19';
const constructs = 'constructs@^10.0.5';

const project = new AwsCdkConstructLibrary({
  name: '@ahammond/cdk-library',
  author: 'Andrew Hammond',
  cdkVersion,
  cdkVersionPinning: true,
  cdkDependencies: ['aws-cdk-lib'],
  deps: ['@types/aws-lambda', 'aws-lambda', 'aws-sdk', constructs, 'multi-convention-namer'],
  devDeps: [
    '@aws-cdk/assert',
    'esbuild',
    'eslint-config-prettier',
    'eslint-plugin-prettier',
    'jsii-release',
    'prettier',
  ],
  peerDeps: [constructs, 'multi-convention-namer'],
  bundledDeps: ['@types/aws-lambda', 'aws-lambda', 'aws-sdk'],
  defaultReleaseBranch: 'main',
  repositoryUrl: 'https://github.com/ahammond/cdk-library.git',

  // ADDED THIS LINE
  packageManager: NodePackageManager.PNPM,
  // END CHANGE

  npmRegistryUrl: 'https://npm.pkg.github.com',
});
```

and then pushed it to GitHub on a branch. Github Action `build` failed:

```
1 Run pnpm i --frozen-lockfile
6 /__w/_temp/781141ff-9e6b-40f4-8c24-4975aa082e85.sh: line 1: pnpm: command not found
7 Error: Process completed with exit code 127.
```

I think that `pnpm` needs to be installed for GitHub actions to work.

Relates to https://github.com/projen/projen/pull/425

### PR DESCRIPTION
**Pull request by ahammond**
- use buildEnabled variable defined above
- fixes #1026 - install pnpm before using it

---
By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license.

### CODE REVIEW

File: src/node-project.ts [hunk 1]
```diff
@@ -851,6 +851,14 @@ export class NodeProject extends GitHubProject {
       });
     }
 
+    if (this.package.packageManager == NodePackageManager.PNPM) {
```
Comment (eladb) [inline src/node-project.ts:854]:
```suggestion
    if (this.package.packageManager === NodePackageManager.PNPM) {
```

**Review by eladb — APPROVED** [review]

**Comment by Chriscbr** [comment]
@ahammond It looks like the build is failing - can you try running "build" again to update the snapshots?
